import type { ReactNode } from 'react';
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import type { CatalogItem, CompanyProfile, DashboardStats, DocumentRecord, InventoryItem, InventoryMovement, ProductionOrder, Shipment, TemplateRecord, User } from '../../types/entities';
interface AppState{ currentUser:User|null; companyProfile:CompanyProfile|null; shipments:Shipment[]; inventory:InventoryItem[]; inventoryMovements:InventoryMovement[]; productionOrders:ProductionOrder[]; documents:DocumentRecord[]; items:CatalogItem[]; templates:TemplateRecord[]; stats:DashboardStats|null; canEdit:boolean; refreshAll:()=>Promise<void>; loginAs:(username:string)=>void; logout:()=>void; }
const AppContext=createContext<AppState|null>(null);
export function AppProvider({children}:{children:ReactNode}){ const [currentUser,setCurrentUser]=useState<User|null>(null); const [companyProfile,setCompanyProfile]=useState<CompanyProfile|null>(null); const [shipments,setShipments]=useState<Shipment[]>([]); const [inventory,setInventory]=useState<InventoryItem[]>([]); const [inventoryMovements,setInventoryMovements]=useState<InventoryMovement[]>([]); const [productionOrders,setProductionOrders]=useState<ProductionOrder[]>([]); const [documents,setDocuments]=useState<DocumentRecord[]>([]); const [items,setItems]=useState<CatalogItem[]>([]); const [templates,setTemplates]=useState<TemplateRecord[]>([]); const [stats,setStats]=useState<DashboardStats|null>(null);
const refreshAll=useCallback(async()=>{ const [boot,shipmentRows,inventoryRows,movementRows,orderRows,documentRows,itemRows,templateRows,dashboardStats]=await Promise.all([api.bootstrap(),api.getShipments(),api.getInventory(),api.getInventoryMovements(),api.getProductionOrders(),api.getDocuments(),api.getItems(),api.getTemplates(),api.getDashboardStats()]); setCurrentUser((prev)=>prev ?? boot.currentUser); setCompanyProfile(boot.companyProfile); setShipments(shipmentRows); setInventory(inventoryRows); setInventoryMovements(movementRows); setProductionOrders(orderRows); setDocuments(documentRows); setItems(itemRows); setTemplates(templateRows); setStats(dashboardStats); },[]);
useEffect(()=>{ void refreshAll(); },[refreshAll]);
const value=useMemo<AppState>(()=>({ currentUser,companyProfile,shipments,inventory,inventoryMovements,productionOrders,documents,items,templates,stats,canEdit:currentUser?.role==='Admin',refreshAll, loginAs(username:string){ const role=username.toLowerCase()==='admin'?'Admin':'Employee'; setCurrentUser({id:role==='Admin'?'u1':'u2',name:role==='Admin'?'Abdelrahman Admin':'Production Employee',username,role}); }, logout(){ setCurrentUser(null); } }),[currentUser,companyProfile,shipments,inventory,inventoryMovements,productionOrders,documents,items,templates,stats,refreshAll]);
return <AppContext.Provider value={value}>{children}</AppContext.Provider>; }
export function useAppState(){ const context=useContext(AppContext); if(!context) throw new Error('useAppState must be used inside AppProvider'); return context; }
