// @ts-nocheck
import { app, dialog } from 'electron';
import fs from 'node:fs';
import path from 'node:path';
import Realm from 'realm';
import { schemas } from './realmSchemas.js';
import { seedData } from './seed.js';
import { DEFAULT_COMPANY_LOGO_DATA_URL } from './defaultCompanyLogo.js';

type AnyRecord=Record<string,any>;
let realm:Realm|null=null;
const collectionMap:Record<string,string>={shipments:'Shipment',inventory:'InventoryItem',inventoryMovements:'InventoryMovement',productionOrders:'ProductionOrder',documents:'DocumentRecord',alerts:'Alert',items:'CatalogItem',templates:'TemplateRecord',users:'User',companyProfiles:'CompanyProfile'};
function id(prefix:string){ return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`; }
function plain<T>(rows:Realm.Results<any>|any[]):T[]{ return Array.from(rows as any).map((row:any)=>JSON.parse(JSON.stringify(row))); }
function defaultShipmentDocuments(){ return JSON.stringify([{name:'Commercial Invoice',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Packing List',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Bill of Lading',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Certificate of Origin',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Customs Papers',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''}]); }
function normalizeShipment(row:any){ return {...row,exchangeRate:Number(row.exchangeRate||1),customsRate:Number(row.customsRate ?? 0.075),vatRate:Number(row.vatRate ?? 0.15),currency:row.currency || 'SAR',documentsJson:row.documentsJson || defaultShipmentDocuments()}; }
function totals(shipmentValue:number, shippingCost:number, customsRate=0.075, vatRate=0.15){ const customsBase=Number(shipmentValue||0)+Number(shippingCost||0); const customs=Number((customsBase*Number(customsRate||0)).toFixed(2)); const vat=Number(((customsBase+customs)*Number(vatRate||0)).toFixed(2)); return {customs,vat,total:Number((customsBase+customs+vat).toFixed(2))}; }
function defaultCompanyProfile(){ return { id:'company-main', companyNameAr:'مهابة الفن للدعاية والإعلان', companyNameEn:'Mahabat Alfan Advertising', brandName:'Mahabat Alfan', activity:'Packaging, printing, advertising and die-cutting', logoDataUrl:DEFAULT_COMPANY_LOGO_DATA_URL, updatedAt:new Date().toISOString() }; }
function dataDir(){ return path.join(app.getPath('userData'),'data'); }
function realmFilePath(){ return path.join(dataDir(),'mapco-erp.realm'); }
function closeRealm(){ if(realm){ try{ realm.close(); }catch{} } realm=null; }
function backupFileName(){ const stamp=new Date().toISOString().replace(/[:.]/g,'-'); return `mahabat-alfan-backup-${stamp}.mabackup`; }
function makeBackupPayload(dbPath:string){ const fileBuffer=fs.existsSync(dbPath) ? fs.readFileSync(dbPath) : Buffer.from(''); return { format:'MahabatAlfanERPBackup', version:1, appName:'مهابة الفن ERP', createdAt:new Date().toISOString(), databaseFile:'mapco-erp.realm', databaseBase64:fileBuffer.toString('base64') }; }
function validateBackupPayload(payload:any){ return payload && payload.format==='MahabatAlfanERPBackup' && payload.databaseBase64; }
function openRealm(){ if(realm) return realm; const dir=dataDir(); fs.mkdirSync(dir,{recursive:true}); realm=new Realm({path:realmFilePath(),schema:schemas as any,schemaVersion:8,onMigration:()=>{}}); seedIfEmpty(realm); ensureCompanyProfile(realm); backfill(realm); return realm; }
function seedIfEmpty(db:Realm){ if(db.objects('Shipment').length) return; db.write(()=>{ seedData.users?.forEach((r:any)=>db.create('User',r)); seedData.shipments.forEach((r:any)=>db.create('Shipment',normalizeShipment(r))); seedData.inventory.forEach((r:any)=>db.create('InventoryItem',r)); seedData.inventoryMovements?.forEach((r:any)=>db.create('InventoryMovement',r)); seedData.productionOrders.forEach((r:any)=>db.create('ProductionOrder',r)); seedData.documents.forEach((r:any)=>db.create('DocumentRecord',r)); seedData.alerts.forEach((r:any)=>db.create('Alert',r)); (seedData as any).items?.forEach((r:any)=>db.create('CatalogItem',r)); (seedData as any).templates?.forEach((r:any)=>db.create('TemplateRecord',r)); }); }
function ensureCompanyProfile(db:Realm){ if(db.objects('CompanyProfile').length) return; db.write(()=>db.create('CompanyProfile', defaultCompanyProfile())); }
function backfill(db:Realm){ db.write(()=>{ db.objects('Shipment').forEach((s:any)=>{ if(!s.documentsJson) s.documentsJson=defaultShipmentDocuments(); if(!s.currency) s.currency='SAR'; if(s.exchangeRate===undefined) s.exchangeRate=1; if(s.customsRate===undefined) s.customsRate=0.075; if(s.vatRate===undefined) s.vatRate=0.15; const t=totals(s.shipmentValue,s.shippingCost,s.customsRate,s.vatRate); s.customs=t.customs; s.vat=t.vat; s.total=t.total; }); db.objects('ProductionOrder').forEach((p:any)=>{ if(!p.materialLinesJson) p.materialLinesJson='[]'; if(p.stockLinked===undefined) p.stockLinked=true; }); db.objects('InventoryMovement').forEach((m:any)=>{ if(m.productionOrderId===undefined) m.productionOrderId=''; }); }); }
function parseLines(order:any){ try{ return JSON.parse(order.materialLinesJson || '[]'); }catch{ return []; } }
function calcProductionCost(payload:any){ const lines=parseLines(payload); const linesCost=lines.reduce((sum:number,line:any)=>sum+Number(line.totalCost||0),0); return Number((linesCost || Number(payload.cost||0)).toFixed(2)); }
function restorePreviousOrderStock(db:Realm, orderId:string){ const movements=Array.from(db.objects('InventoryMovement').filtered('productionOrderId == $0',orderId)); movements.forEach((movement:any)=>{ const item=db.objectForPrimaryKey('InventoryItem',movement.itemId); if(item && movement.type==='out'){ item.quantity=Number(item.quantity||0)+Number(movement.quantity||0); item.totalValue=item.quantity*item.unitCost; } db.delete(movement); }); }
function applyProductionStock(db:Realm, order:any){ const lines=parseLines(order); lines.forEach((line:any)=>{ const item=db.objectForPrimaryKey('InventoryItem',line.inventoryItemId); if(!item) return; const qty=Number(line.quantity||0); item.quantity=Math.max(0,Number(item.quantity||0)-qty); item.totalValue=item.quantity*item.unitCost; db.create('InventoryMovement',{id:id('MOV'),itemId:item.id,itemName:item.itemName,type:'out',quantity:qty,date:order.startDate,notes:`صرف تلقائي لأمر الإنتاج ${order.orderNo} - ${line.componentType}`,productionOrderId:order.id}); }); }
export const realmService={
 bootstrap(){ const db=openRealm(); return {currentUser:plain<any>(db.objects('User'))[0], companyProfile:this.companyProfile(), shipments:this.list('shipments'), inventory:this.list('inventory'), inventoryMovements:this.list('inventoryMovements'), productionOrders:this.list('productionOrders'), documents:this.list('documents'), alerts:this.list('alerts'), items:this.list('items'), templates:this.list('templates')}; },
 companyProfile(){ const db=openRealm(); ensureCompanyProfile(db); return plain<any>(db.objects('CompanyProfile'))[0]; },
 updateCompanyProfile(payload:AnyRecord){ const db=openRealm(); ensureCompanyProfile(db); let out:AnyRecord={}; db.write(()=>{ const row=db.objectForPrimaryKey('CompanyProfile','company-main'); if(!row) throw new Error('Company profile not found'); Object.entries(payload).forEach(([k,v])=>{ if(v!==undefined) row[k]=v as never; }); row.updatedAt=new Date().toISOString(); out=JSON.parse(JSON.stringify(row)); }); return out; },
 stats(){ const shipments=this.list<any>('shipments'), inventory=this.list<any>('inventory'), orders=this.list<any>('productionOrders'), docs=this.list<any>('documents'); return {shipmentsValue:shipments.reduce((s,r)=>s+r.total,0), customsValue:shipments.reduce((s,r)=>s+r.customs,0), inventoryValue:inventory.reduce((s,r)=>s+r.totalValue,0), productionCost:orders.reduce((s,r)=>s+r.cost,0), ordersCount:orders.length, missingDocuments:docs.filter(d=>d.status==='ناقص').length, lowStockItems:inventory.filter(i=>i.quantity<=i.reorderLevel).length}; },
 list<T=AnyRecord>(kind:string){ const db=openRealm(); return plain<T>(db.objects(collectionMap[kind])); },
 create(kind:string,payload:AnyRecord){ const db=openRealm(); const name=collectionMap[kind]; const prefix={shipments:'SHP',inventory:'ITM',inventoryMovements:'MOV',productionOrders:'PRD',documents:'DOC',items:'CAT',templates:'TPL'}[kind] ?? 'REC'; let record={...payload,id:payload.id ?? id(prefix)}; if(kind==='shipments'){ record=normalizeShipment(record); record={...record,...totals(Number(record.shipmentValue||0),Number(record.shippingCost||0),Number(record.customsRate ?? 0.075),Number(record.vatRate ?? 0.15))}; }
 if(kind==='inventory') record={...record,quantity:Number(record.quantity||0),unitCost:Number(record.unitCost||0),reorderLevel:Number(record.reorderLevel||0),totalValue:Number(record.quantity||0)*Number(record.unitCost||0)};
 if(kind==='productionOrders'){ record={...record,materialLinesJson:record.materialLinesJson || '[]',stockLinked:record.stockLinked ?? true}; record.cost=calcProductionCost(record); record.material=JSON.parse(record.materialLinesJson || '[]').map((l:any)=>l.componentType).join(' + ') || record.material || 'Die components'; }
 db.write(()=>{ db.create(name,record); if(kind==='productionOrders' && record.stockLinked) applyProductionStock(db,record); }); return record; },
 update(kind:string,recordId:string,payload:AnyRecord){ const db=openRealm(); const name=collectionMap[kind]; let out:AnyRecord={}; db.write(()=>{ const row=db.objectForPrimaryKey(name,recordId); if(!row) throw new Error('Record not found'); if(kind==='productionOrders') restorePreviousOrderStock(db,recordId); Object.entries(payload).forEach(([k,v])=>{ if(v!==undefined) row[k]=v as never; }); if(kind==='shipments'){ const t=totals(Number(row.shipmentValue||0),Number(row.shippingCost||0),Number(row.customsRate ?? 0.075),Number(row.vatRate ?? 0.15)); row.customs=t.customs; row.vat=t.vat; row.total=t.total; if(!row.documentsJson) row.documentsJson=defaultShipmentDocuments(); }
 if(kind==='inventory'){ row.quantity=Number(row.quantity||0); row.unitCost=Number(row.unitCost||0); row.reorderLevel=Number(row.reorderLevel||0); row.totalValue=row.quantity*row.unitCost; }
 if(kind==='productionOrders'){ row.cost=calcProductionCost(row); row.material=parseLines(row).map((l:any)=>l.componentType).join(' + ') || row.material; if(row.stockLinked) applyProductionStock(db,row); }
 out=JSON.parse(JSON.stringify(row)); }); return out; },
 delete(kind:string,recordId:string){ const db=openRealm(); db.write(()=>{ if(kind==='productionOrders') restorePreviousOrderStock(db,recordId); const row=db.objectForPrimaryKey(collectionMap[kind],recordId); if(row) db.delete(row); }); return true; },
 stockMovement(payload:AnyRecord){ const db=openRealm(); let movement:any; db.write(()=>{ const item=db.objectForPrimaryKey('InventoryItem',payload.itemId); if(!item) throw new Error('Inventory item not found'); const qty=Number(payload.quantity||0); if(payload.type==='in') item.quantity+=qty; else if(payload.type==='out') item.quantity=Math.max(0,item.quantity-qty); else if(payload.type==='adjustment') item.quantity=qty; item.totalValue=item.quantity*item.unitCost; movement={id:id('MOV'),itemId:item.id,itemName:item.itemName,type:payload.type,quantity:qty,date:payload.date,notes:payload.notes ?? '',productionOrderId:payload.productionOrderId ?? ''}; db.create('InventoryMovement',movement); }); return movement; },
 backupStatus(){ const db=openRealm(); const dbPath=realmFilePath(); return { databasePath:dbPath, exists:fs.existsSync(dbPath), sizeBytes:fs.existsSync(dbPath) ? fs.statSync(dbPath).size : 0, records:{shipments:db.objects('Shipment').length, inventory:db.objects('InventoryItem').length, productionOrders:db.objects('ProductionOrder').length, documents:db.objects('DocumentRecord').length, items:db.objects('CatalogItem').length, templates:db.objects('TemplateRecord').length} }; },
 async createBackup(){ openRealm(); const dbPath=realmFilePath(); closeRealm(); const result=await dialog.showSaveDialog({title:'إنشاء نسخة احتياطية', defaultPath:backupFileName(), filters:[{name:'Mahabat Alfan ERP Backup',extensions:['mabackup']},{name:'Realm Database',extensions:['realm']}]}); if(result.canceled || !result.filePath){ openRealm(); return {canceled:true,path:''}; } const target=result.filePath; if(target.toLowerCase().endsWith('.realm')){ fs.copyFileSync(dbPath,target); } else { const payload=makeBackupPayload(dbPath); fs.writeFileSync(target,JSON.stringify(payload,null,2),'utf8'); } openRealm(); return {canceled:false,path:target,createdAt:new Date().toISOString()}; },
 async restoreBackup(){ const result=await dialog.showOpenDialog({title:'استيراد نسخة احتياطية', properties:['openFile'], filters:[{name:'ERP Backup',extensions:['mabackup','realm']},{name:'All Files',extensions:['*']}]}); if(result.canceled || !result.filePaths[0]) return {canceled:true,path:''}; const source=result.filePaths[0]; const target=realmFilePath(); closeRealm(); fs.mkdirSync(dataDir(),{recursive:true}); const beforeRestore=path.join(dataDir(),`before-restore-${Date.now()}.realm`); if(fs.existsSync(target)) fs.copyFileSync(target,beforeRestore); if(source.toLowerCase().endsWith('.realm')){ fs.copyFileSync(source,target); } else { const payload=JSON.parse(fs.readFileSync(source,'utf8')); if(!validateBackupPayload(payload)) throw new Error('ملف النسخة الاحتياطية غير صحيح'); fs.writeFileSync(target,Buffer.from(payload.databaseBase64,'base64')); } openRealm(); return {canceled:false,path:source,restoredAt:new Date().toISOString(),previousBackup:fs.existsSync(beforeRestore)?beforeRestore:''}; },
 async chooseFile(){ const result=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'Documents',extensions:['pdf','png','jpg','jpeg','doc','docx','xls','xlsx','dxf','svg','html']},{name:'All Files',extensions:['*']}]}); return result.canceled ? '' : result.filePaths[0]; },
 async exportReport(kind:string){ const rows=this.list<any>({shipments:'shipments',inventory:'inventory',production:'productionOrders',documents:'documents',items:'items',templates:'templates'}[kind] ?? kind); const headers=Object.keys(rows[0] ?? {}); const content='\ufeff'+[headers.join(','),...rows.map(row=>headers.map(h=>JSON.stringify(row[h] ?? '')).join(','))].join('\n'); const result=await dialog.showSaveDialog({defaultPath:`${kind}-report.csv`,filters:[{name:'CSV',extensions:['csv']}]}); if(result.canceled || !result.filePath) return ''; fs.writeFileSync(result.filePath,content,'utf8'); return result.filePath; }
};
