name: Build ERP EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: mapco-erp-execution   # 🔥 الحل هنا

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Build Windows EXE
        run: npx electron-builder --win nsis --x64 --publish never

      - name: Show files
        run: dir dist

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ERP-EXE
          path: mapco-erp-execution/dist/**
